### ISSUE TITLE
Remove password

### ISSUE THREAD

**Issue by mohamedgamil22** [mohamedgamil22/CI-CD#12]
we need a solution to remove the password from the script

**Comment by mohamedgamil22** [comment]
@fadymaherelgendy i've made an environmental variable on the jenkins test for the password.
"MG_TENANT_PASS"
i recommend the solution,to check if the variable is set, if not ask the user to enter one, 
this can be made from the main.sh script or the python script.

**Comment by fadymaherelgendy** [comment]
There is also a convenient solution on using the password plugin.
https://wiki.jenkins.io/display/JENKINS/Credentials+Binding+Plugin

**Comment by fadymaherelgendy** [comment]
Done using Jenkins built in Bindings

**Comment by mohamedgamil22** [comment]
Perfect, i have adjusted the parameters of the main jenkins test to match the variables in your script

Thanks @fadymaherelgendy
